
#! QP solvers
# Python system control deps
RUN pip3 install --upgrade \
    qpsolvers \
    quadprog gurobipy osqp cvxopt cvxpy

# # install CVXOPT (https://cvxopt.org/)
RUN pip3 install --upgrade cvxopt

# # install CVXPY (https://www.cvxpy.org/index.html)
RUN pip3 install --upgrade cvxpy

# # install Guroby ()
RUN pip3 install --upgrade gurobipy

# # install osqp ()
RUN pip3 install --upgrade osqp


# Python system control deps
RUN pip3 install --upgrade \
    qpsolvers \
    quadprog gurobipy osqp cvxopt cvxpy


#! Bazel (https://bazel.build/install/ubuntu)
RUN curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel-archive-keyring.gpg
RUN mv bazel-archive-keyring.gpg /usr/share/keyrings
RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
RUN apt update && apt install --quiet -y bazel




