ARG ROS_DISTRO

FROM $ROS_DISTRO as base-stage

ARG DEBIAN_FRONTEND=noninteractive

ARG UBUNTU_USER=docker_user
ARG UBUNTU_PSW=docker
ARG UBUNTU_UID=1000
ARG UBUNTU_GID=1000

ENV UBUNTU_USER=$UBUNTU_USER
ENV UBUNTU_PSW=$UBUNTU_PSW
ENV UBUNTU_UID=$UBUNTU_UID
ENV UBUNTU_GID=1000

# Create local user docker_user
RUN useradd -r -m -d /home/$UBUNTU_USER -s /bin/bash -g root -G sudo -G dialout -u $UBUNTU_UID -p "$(openssl passwd -6 $UBUNTU_PSW)" $UBUNTU_USER

# Add local user to system groups
RUN usermod -aG sudo $UBUNTU_USER
RUN usermod -aG dialout $UBUNTU_USER
RUN usermod -aG tty $UBUNTU_USER
RUN usermod -aG audio $UBUNTU_USER
RUN usermod -aG video $UBUNTU_USER

# Update
RUN apt update


########################
# INSTALL DEPENDENCIES #
########################

# Ubuntu deps
RUN apt install --quiet -y \
    sudo software-properties-common lsb-release \
    apt-transport-https ca-certificates gnupg gnupg2 gnupg-agent libssl-dev \
    curl file wget zip unzip pkg-config openssh-client openssh-server \
    xterm tmux gdb valgrind \
    htop net-tools nmap

# C++ deps
RUN apt install --quiet -y \
    build-essential \
    clang \
    cmake \
    ccache \
	ninja-build

# C++ linter
RUN apt install --quiet -y \
    clang-tidy clang-tools \
    cppcheck \
    astyle

# C++ testing deps
RUN apt install --quiet -y \
    libgtest-dev \
    libgmock-dev \
    lcov

# C++ common lib
RUN apt install --quiet -y \
    libboost-all-dev \
    libeigen3-dev

# Python deps
RUN apt install --quiet -y \
    python3 \
    python3-dev \
    python3-pip

RUN pip3 install --upgrade \
    wheel \
    setuptools \
    argcomplete

# Python linter
RUN pip3 install --upgrade \
    pylint \
    flake8 \
    mypy

RUN pip3 install --upgrade \
    pytest==7.1.3 \
    pytest-mock \
    pytest-cov pytest-html \
    pytest-pep8 \
    pytest-pylint \
    pytest-flake8

RUN pip3 install --upgrade \
    pandas tk matplotlib \
    pyyaml \
    numpy scipy

# Python parsers
RUN pip3 install --upgrade \
    pyyaml \
    jsonschema \
    jinja2 \
    toml


# Python system control deps
RUN pip3 install --upgrade \
    qpsolvers \
    quadprog gurobipy osqp cvxopt cvxpy

# # install CVXOPT (https://cvxopt.org/)
# RUN pip3 install --upgrade cvxopt

# # install CVXPY (https://www.cvxpy.org/index.html)
# RUN pip3 install --upgrade cvxpy

# # install Guroby ()
# RUN pip3 install --upgrade gurobipy

# # install osqp ()
# RUN pip3 install --upgrade osqp




#! gazebo-stage
# FROM base-stage as gazebo-stage


#! ignition-stage
# FROM base-stage as ignition-stage

# Install Gazebo Ignition
# RUN sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
# RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
# RUN apt update





#! px4-stage
# FROM base-stage as px4-stage

RUN apt install --quiet -y openjdk-11-jdk

# Data serialization
RUN apt install --quiet -y \
    protobuf-compiler

# X11
RUN apt install --quiet -y \
    libx11-dev \
    libxrandr-dev \
    libxi-dev \
    libxinerama-dev

# ROS
RUN pip3 install --upgrade \
    pyros-genmsg

# Others
RUN pip3 install --upgrade \
    empy


# Clean
RUN apt -y autoremove \
	&& apt clean autoclean \
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*


#! px4-1.14-stage (https://docs.px4.io/main/en/ros/ros2_comm.html#humble)
# FROM base-stage as px4-1.14-stage

#TODO PX4 Flight controller (NEW)
RUN pip3 install --upgrade kconfiglib

# Set user
USER $UBUNTU_USER
WORKDIR /home/$UBUNTU_USER

# Clone PX4 stack
RUN git clone --recursive https://github.com/PX4/PX4-Autopilot.git
RUN echo $UBUNTU_PSW | sudo -S bash PX4-Autopilot/Tools/setup/ubuntu.sh
# RUN echo $UBUNTU_PSW | sudo -S bash PX4-Autopilot/Tools/setup/ubuntu.sh --no-sim-tools
RUN cd PX4-Autopilot/ && make px4_sitl
#TODO delete source and intermediate files


# Setup Micro XRCE-DDS Agent & Client
RUN git clone https://github.com/eProsima/Micro-XRCE-DDS-Agent.git
RUN cd Micro-XRCE-DDS-Agent \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make \
    && echo $UBUNTU_PSW | sudo -S make install \
    && echo $UBUNTU_PSW | sudo -S ldconfig /usr/local/lib/







##############
# ENTRYPOINT #
##############

# Set entrypoint
COPY ./docker/ros2_entrypoint.sh /
ENTRYPOINT ["/ros2_entrypoint.sh"]

ENV force_color_prompt=yes
CMD ["bash"]